### ISSUE TITLE
T-001 `Geno` data object. Check and write/edit documentation for it.

### ISSUE THREAD

**Issue by eriqande** [eriqande/gscramble#24]

**Comment by eriqande** [comment]
See [https://r-pkgs.org/data.html#documenting-data](https://r-pkgs.org/data.html#documenting-data) for a good overview of how to document data.

**Comment by rmgiglio** [comment]
Add rownames to Geno to match I_meta

**Comment by rmgiglio** [comment]
Add NAs to the data to check all the functions handle missing data properly. Make sure there is at least one NA genotype within the first few individuals and first few loci

**Comment by eriqande** [comment]
This looks all done to me!
