### ISSUE TITLE
T-001  `I_meta` data object. Check and write/edit documentation for it.

### ISSUE THREAD

**Issue by eriqande** [eriqande/gscramble#25]

**Comment by rmgiglio** [comment]
Need to change pop IDs to be 1-4 rather than 2,3,4,10

**Comment by rmgiglio** [comment]
Need to write function to compare Geno rownames to I_meta IDs

**Comment by rmgiglio** [comment]
Pop IDs also need to be changed in RepPop, RepPop1, and RepPop4
