### ISSUE TITLE
plot_simulated_chromosome_segments overwriting inds with the sample Rep x ID combinations

### ISSUE THREAD

**Issue by tjsmyser** [eriqande/gscramble#38]
Code producing bug:

Input_tibble <- tibble(
  gpp = list(GSP, gsp4),
  reppop = list(RepPop1, RepPop4)
)

set.seed(15) # for reproducibility
Segments <- segregate(
  request = Input_tibble,
  RR = RecRates
)

g <- plot_simulated_chromomsome_segments(Segments, RecRates)
g

Also, coercing unique Rep x ID combinations with the following code produces a different bug

RepPop4_temp <- RepPop4
RepPop4_temp$rep <- RepPop4_temp$rep + 2

Input_tibble <- tibble(
  gpp = list(GSP, gsp4),
  reppop = list(RepPop1, RepPop4_temp)
)

Segments <- segregate(
  request = Input_tibble,
  RR = RecRates
)

g <- plot_simulated_chromomsome_segments(Segments, RecRates)
g

This might suggest the $rep column in reppop inputs is specifically expecting values 1:(n_reps).

However, if we carry this to have reps >4, I seem to be producing a bug in which the sparklines are present but the recombined chromosomes are lost:

RepPop4_temp <- rbind(RepPop4_temp, RepPop4_temp)

seq(from = 1, to = 6, rep(4))

RepPop4_temp$rep <- rep(1:6, each = 4)

Input_tibble <- tibble(
  gpp = list(gsp4),
  reppop = list(RepPop4_temp)
)

# here is what that input object looks like:
Input_tibble

set.seed(15) # for reproducibility
Segments <- segregate(
  request = Input_tibble,
  RR = RecRates
)

g <- plot_simulated_chromomsome_segments(Segments, RecRates)
g

**Comment by eriqande** [comment]
Thanks for catching this Tim.  I fixed it by making sure that the facet units included the GSP in there, too!
