### ISSUE TITLE
Release gscramble 1.0.0

### ISSUE THREAD

**Issue by eriqande** [eriqande/gscramble#43]
First release:

* [x] `usethis::use_news_md()`
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')  THIS IS A US GOVT WORK, SO IT IS NOT SUBJECT TO COPYRIGHT.  I AM GOING TO LEAVE cph out o sj=
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `usethis::use_github_links()`
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] #44
* [x] `devtools::check_win_devel()`
* [x] `git push`
* [ ] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] Add preemptive link to blog post in pkgdown news menu
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`
* [ ] `usethis::use_news_md()`
* [ ] Finish blog post
* [ ] Tweet

**Comment by mgdesaix** [comment]
For the things I ticked off above (or about to tick):
1) I think the installation instructions look good - unless the aspirational part is that it will be on CRAN so it should just be `install.packages("gscramble")`? I didn't change anything
2) I added a title and description - feel free to edit
3) gscramble2newhybrids.R is lacking @examples and @return; segments2markers.R and plink_map2rec_rates.R are lacking just the @return. I can get those bits added shortly

**Comment by eriqande** [comment]
It is up on CRAN
