### ISSUE TITLE
`devtools::check(remote = TRUE, manual = TRUE)`

### ISSUE THREAD

**Issue by mgdesaix** [eriqande/gscramble#44]
The devtools::check() produces a NOTE of the following. I couldn't resolve the note through some Googling, I did see some folks' mention of it that seems it's not an issue? Everything else looked good

```
checking HTML version of manual ... NOTE
  Found the following HTML validation problems:
  GSP.html:4:1 (GSP.Rd:6): Warning: <link> inserting "type" attribute...
```

**Comment by eriqande** [comment]
That is weird. I took the parentheses out of the title, if that is what was triggering a roxygen link that went nowhere...

It doesn't show up in `check_win()` so I think we should be fine.

Thanks!

eric
